                <!--div class="project-card hidden">
                    <h3 data-langkey="p1_title">Trading Journal App</h3>
                    <p data-langkey="p1_desc">Web app untuk mencatat dan menganalisis histori trading.</p>
                    <div class="project-buttons">
						<a href="#" class="btn"><i class="fas fa-eye"></i> <span data-langkey="btn_demo">Demo</span></a>
						<a href="#" class="btn"><i class="fab fa-github"></i> GitHub</a>
                    </div>
                </div>
                <div class="project-card hidden">
                    <h3 data-langkey="p2_title">WhatsApp AI Chatbot</h3>
                    <p data-langkey="p2_desc">Chatbot WA pakai Node.js via Termux dengan integrasi AI.</p>
                    <div class="project-buttons">
	                    <a href="#" class="btn"><i class="fab fa-github"></i> GitHub</a>
                    </div>
                </div>
                <div class="project-card hidden">
                    <h3 data-langkey="p3_title">IoT Pump Indicator</h3>
                    <p data-langkey="p3_desc">Sensor pompa air otomatis dengan notifikasi via web dan MQTT.</p>
                    <div class="project-buttons">
						<a href="#" class="btn"><i class="fas fa-video"></i> <span data-langkey="btn_video">Video</span></a>
						<a href="#" class="btn"><i class="fab fa-github"></i> GitHub</a>
                    </div>
                </div>
                <div class="project-card hidden">
                    <h3 data-langkey="p4_title">FX Personal Website</h3>
                    <p data-langkey="p4_desc">Website portofolio ini. Dibuat dengan HTML, CSS & JS.</p>
                    <div class="project-buttons">
						<a href="#" class="btn"><i class="fas fa-code"></i> <span data-langkey="btn_source">Source Code</span></a>
                    </div>
                </div-->
